import{a as S,S as B,i}from"./assets/vendor-LK6CqzKq.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const g of a.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&n(g)}).observe(document,{childList:!0,subtree:!0});function r(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(t){if(t.ep)return;t.ep=!0;const a=r(t);fetch(t.href,a)}})();const P="https://pixabay.com/api/",q="51504630-db9fa299e862fff98d3dacf4e";async function y(o,e=1){var r;try{return(await S.get(P,{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}catch(n){throw console.error("Pixabay API error:",((r=n.response)==null?void 0:r.data)||n.message),new Error("Failed to fetch images")}}const v=document.querySelector(".gallery"),u=document.querySelector(".loader"),m=document.querySelector(".load-more-btn"),x=new B(".gallery a");function b(o){const e=o.map(r=>`
    <a href="${r.largeImageURL}" class="photo-card">
      <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
      <div class="info">
        <p><b>Likes:</b> ${r.likes}</p>
        <p><b>Views:</b> ${r.views}</p>
        <p><b>Comments:</b> ${r.comments}</p>
        <p><b>Downloads:</b> ${r.downloads}</p>
      </div>
    </a>
  `).join("");v.insertAdjacentHTML("beforeend",e),x.refresh()}function M(){v.innerHTML=""}function L(){u&&u.classList.add("visible")}function l(){u&&u.classList.remove("visible")}function E(){m&&m.classList.add("visible")}function h(){m&&m.classList.remove("visible")}let s=1,d="",c=0,f=!1,w=!1;const $=document.querySelector("form"),p=document.querySelector(".load-more-btn");$.addEventListener("submit",async o=>{if(o.preventDefault(),d=o.target.elements["search-text"].value.trim(),!!d){s=1,w=!1,M(),h(),L();try{const e=await y(d,s);if(c=e.totalHits,e.hits.length===0){i.info({message:"No images found. Try another search."}),l();return}b(e.hits),l(),c>15&&(p.textContent="Load More",E())}catch{i.error({message:"Error loading images. Please try again."}),l()}}});p.addEventListener("click",async()=>{s+=1,h(),L();try{const o=await y(d,s);b(o.hits),l(),s===2&&c>s*15&&(p.textContent="Scroll to load more",E()),s>=3&&(w=!0,h()),s*15>=c&&i.info({message:"You've reached the end of search results."});const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}catch{i.error({message:"Error loading more images."}),l()}});window.addEventListener("scroll",async()=>{if(!w||f)return;const{scrollTop:o,scrollHeight:e,clientHeight:r}=document.documentElement;if(o+r>=e-5){if(s*15>=c)return;s+=1,f=!0,i.info({message:"Loading images, please wait...",position:"bottomCenter",timeout:2e3,progressBar:!1,close:!1}),L();try{const n=await y(d,s);b(n.hits),l(),f=!1,s*15>=c&&i.info({message:"You've reached the end of search results."})}catch{i.error({message:"Error loading more images."}),l(),f=!1}}});
//# sourceMappingURL=index.js.map
