import{a as g,S as b,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function u(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const L="https://pixabay.com/api/",w="51504630-db9fa299e862fff98d3dacf4e";async function f(r,e){try{return(await g.get(L,{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}catch{throw new Error("Failed to fetch images")}}const m=document.querySelector(".gallery"),y=document.querySelector("#load-more"),v=document.querySelector(".loader"),S=new b(".gallery a");function h(r){const e=r.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o.likes}</p>
        <p><b>Views:</b> ${o.views}</p>
        <p><b>Comments:</b> ${o.comments}</p>
        <p><b>Downloads:</b> ${o.downloads}</p>
      </div>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",e),S.refresh()}function q(){m.innerHTML=""}function c(){v.classList.add("hidden")}function $(){y.classList.remove("hidden")}function p(){y.classList.add("hidden")}const B=document.querySelector("form"),M=document.querySelector("input"),E=document.querySelector("#load-more");let i="",n=1,d=0;B.addEventListener("submit",async r=>{if(r.preventDefault(),i=M.value.trim(),n=1,i===""){a.error({message:"Please enter a search term"});return}q(),p();try{const e=await f(i,n);if(c(),e.totalHits===0){a.error({message:"No images found"});return}h(e.hits),a.success({message:`Hooray! We found ${e.totalHits} images`}),d=Math.ceil(e.totalHits/15),n<d?$():a.info({message:"We're sorry, but you've reached the end of search results."})}catch{c(),a.error({message:"Error loading images"})}});E.addEventListener("click",async()=>{n++;try{const r=await f(i,n);c(),h(r.hits),P(),n>=d&&(p(),a.info({message:"We're sorry, but you've reached the end of search results."}))}catch{c(),a.error({message:"Failed to load more images"})}});function P(){const r=document.querySelector(".gallery-item");if(!r)return;const e=r.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
